language: java
jdk: oraclejdk8

env:
  global:
  - ENCRYPTION_LABEL: "7bb7dfe9ff97"

install: "./gradlew setupCIWorkspace"
script:
 - "./gradlew build"
after_success:
 - "./scripts/updateJavadoc"
 - "./scripts/updateWiki"
 - "./gradlew bintrayUpload"

notifications:
  email: false
