language: java
jdk: oraclejdk8

install: "./gradlew setupCIWorkspace"
script:
 - "./gradlew build"
after_success:
 - "./scripts/updateJavadoc"
 - "./gradlew bintrayUpload"

notifications:
  email: false