#!/usr/bin/env bash
./gradlew javadoc

git clone --depth=50 --branch=gh-pages https://github.com/LousyLynx/On-The-Fly.git gh-pages
cd gh-pages

cp ../build/docs/javadoc/* wiki
git add .
git commit -m "Updating javadoc"
git push https://github.com/LousyLynx/On-The-Fly.git gh-pages

cd ../